chat/urls.py
from django.urls import path

from .views import index_view, room_view, logout

app_name = "chat"

urlpatterns = [
    path("", index_view, name="chat-index"),
    path("<str:room_name>/", room_view, name="chat-room"),
    path("logout", logout, name="logout"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

from core.settings import MEDIA_URL, MEDIA_ROOT
from chat.views import login_view, signup_view, login_required_view, account_settings

urlpatterns = [
    path("", login_view, name="index-page"),
    path("login-required", login_required_view, name="login-required"),
    # path('reg', SignUpView.as_view(), name='reg-page'),
    path("reg", signup_view, name="reg-page"),
    path("chat/", include("chat.urls")),
    path("account-settings", account_settings, name="account-settings"),
    path("admin/", admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

chat/models.py
import os
import json
from datetime import datetime

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _

from core.settings import MEDIA_URL, MEDIA_ROOT, DEFAULT_AVATAR_ROOT


# TODO: fix structure of project for attachments and avatars and examples images
# TODO: add scripts for manage.py for quickstart project on new machine(automate)
class Avatar(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='avatar')
    photo = models.ImageField(blank=False, default=DEFAULT_AVATAR_ROOT, upload_to="avas")

    def __str__(self):
        return f"{self.user.username} avatar"

    def url(self):
        return os.path.join(MEDIA_URL, str(self.photo))

    def get_photo(self):
        # used in the admin site model as a "thumbnail"
        # TODO: create thumbnail
        html = '<img src="{}" width="150" height="150" />'
        return mark_safe(html.format(self.url()))


class Room(models.Model):
    name = models.CharField(max_length=128)
    online = models.ManyToManyField(to=User, blank=True)

    def get_online_count(self):
        return self.online.count()

    def join(self, user):
        self.online.add(user)
        self.save()

    def __str__(self):
        return f"{self.name} ({self.get_online_count()})"


class PersonalChat(models.Model):
    pass


class CommunityChat(models.Model):
    pass


class MessageType(models.TextChoices):
    PUBLIC = 'PUBLIC', _('Public')
    PRIVATE = 'PRIVATE', _('Private')


class Message(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='message'
    )
    room = models.ForeignKey(to=Room, on_delete=models.CASCADE)
    content = models.CharField(max_length=512)
    msg_type = models.CharField(
        max_length=7,
        choices=MessageType.choices,
        default=MessageType.PUBLIC
    )
    to = models.ForeignKey(
        to=User,
        on_delete=models.PROTECT,
        null=True,
        default=None,
        related_name='private_message'
    )
    timestamp = models.DateTimeField(auto_now_add=True)

    def json(self):
        attachment = self.attachment.first()
        msg = {
            'username': str(self.user),
            'room': str(self.room),
            'content': self.content,
            'avatar_url': self.user.avatar.photo.url,
            'timestamp': datetime.isoformat(self.timestamp),
        }

        if attachment:
            attachment_url = attachment.url()
            msg["attachment"] = attachment_url

        return json.dumps(msg)

    def get_timestamp(self):
        return datetime.isoformat(self.timestamp)

    def get_attachment_url(self):
        attachment = self.attachment.first()
        if attachment:
            return attachment.url()
        raise Exception("Message hasn't attachment!!!")

    def __str__(self):
        return f"{self.user.username}: {self.content} [{self.timestamp}]"


class Attachment(models.Model):
    message = models.ForeignKey(
        to=Message, on_delete=models.CASCADE, related_name="attachment"
    )
    photo = models.ImageField(upload_to="attachments", blank=False)
    name = models.CharField(max_length=128, unique=True, default="qq")

    def url(self):
        return os.path.join(MEDIA_URL, "attachments", self.name)

    def photo_tag(self):
        # used in the admin site model as a "thumbnail"
        # TODO: create thumbnail
        html = '<img src="{}" width="150" height="150" />'
        return mark_safe(html.format(self.url()))

    photo_tag.short_description = "Photo"

    def delete_file(self):
        filepath = os.path.join(MEDIA_ROOT, "attachments", self.name)
        try:
            os.remove(filepath)
        except FileNotFoundError:
            print(f"{filepath} not found")

    def __str__(self):
        return f"{self.message}"


@receiver(post_delete, sender=Attachment)
def delelte_attachment_file(sender, instance, using, **kwargs):
    instance.delete_file()

chat/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Avatar


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RegisterForm(UserCreationForm):
    username = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ("username", "password1", "password2")

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.username = self.cleaned_data["username"]
        if commit:
            user.save()
        avatar = Avatar.objects.create(user=user)
        avatar.save()
        return user


class AccountPhotoUpdateForm(forms.Form):
    photo = forms.ImageField(required=True)

chat/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout as lgt
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.core.paginator import Paginator
from django.db.models import Q

from .models import Avatar, Message, Room
from .forms import LoginForm, RegisterForm, AccountPhotoUpdateForm


@require_http_methods(["GET", "POST"])
def login_view(req):
    if req.method == "GET":
        user = req.user
        if user.is_authenticated:
            return redirect("chat:chat-index")
        form = LoginForm()
        return render(
            req,
            "login.html",
            {
                "form": form,
            },
        )

    if req.method == "POST":
        next_page = req.GET.get("next", "chat:chat-index")
        form = LoginForm(req.POST)
        if form.is_valid():
            cd = form.cleaned_data
            username = cd["username"]
            password = cd["password"]
            user = authenticate(username=username, password=password)
            if user is None:
                return HttpResponse("Wrong password or username")
            login(req, user)
            return redirect(next_page)


@require_http_methods(["GET"])
@login_required(login_url="login-required")
def index_view(req):
    return render(
        req,
        "index.html",
        {
            "rooms": Room.objects.all(),
        },
    )


@require_http_methods(["GET"])
@login_required(login_url="login-required")
def room_view(req, room_name):
    chat_room, created = Room.objects.get_or_create(name=room_name)
    paginator = Paginator(Message.objects.filter(
        Q(room=chat_room),
        Q(msg_type='PUBLIC') | Q(to=req.user) | Q(user=req.user)
    ).all().order_by('-timestamp'), 5)
    messages = paginator.get_page(1)
    return render(
        req,
        "room.html",
        {
            "room": chat_room,
            "messages": reversed(messages),
        },
    )


@login_required
def logout(req):
    lgt(req)
    return redirect("index-page")


@require_http_methods(["GET", "POST"])
def signup_view(req):
    form = RegisterForm(req.POST)
    if form.is_valid():
        form.save()
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(username=username, password=password)
        login(req, user)
        next_page = req.GET.get("next", "chat:chat-index")
        return redirect(next_page)
    else:
        form = RegisterForm()
    return render(req, "reg.html", {"form": form})


@require_http_methods(["GET"])
def login_required_view(req):
    next_page = req.GET.get("next", None)
    return render(req, "login_required.html", {"next_page": next_page})


@require_http_methods(["GET", "POST"])
def account_settings(req):
    # TODO: Crop avatar
    if req.method == "GET":
        form = AccountPhotoUpdateForm()
        return render(
            req,
            "account_settings.html",
            {
                "form": form,
                "prev_photo": Avatar.objects.get(user=req.user).photo.url,
            },
        )
    if req.method == "POST":
        form = AccountPhotoUpdateForm(req.POST, req.FILES)
        if form.is_valid():
            photo = form.cleaned_data["photo"]
            print(photo)
            avatar = Avatar.objects.get(user=req.user)
            avatar.photo = photo
            avatar.save()
            return HttpResponse("OK")
        return HttpResponse("Wrong!", 405)

chat/templates/account_settings.html
{% load static %}

<h1>You settings</h1>

<form method="post"  enctype="multipart/form-data" id="form_img">
  {{ form.as_p }} {% csrf_token %}
  <img id="img_id" src="{{ prev_photo }}" alt="your image" />
  <p><input type="submit" value="Save" /></p>
</form>

<script src="{% static 'account_settings.js' %}"></script>

chat/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock title %}</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
    />
    <link rel="shortcut icon" href="{% static 'favicon-16x16.png' %}" type="image/x-icon">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/58d65ee514.js" crossorigin="anonymous"></script>
    {% block style %}{% endblock style %}
  </head>
  <body>
    {% include "navbar.html" %}
    <div id="content">{% block content %} {% endblock %}</div>
  </body>
</html>

chat/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} 
  django-channels-chat 
{% endblock title %} 

{% block style %}
<style>
  #roomSelect {
    height: 300px;
  }
</style>
{% endblock style %} {% block content %}
<div class="container mt-3 p-5">
  <h2>django-channels-chat</h2>
  <div class="row">
    <div class="col-12 col-md-8">
      <div class="mb-2">
        <label for="roomInput">Enter a room name to connect to it:</label>
        <input
          type="text"
          class="form-control"
          id="roomInput"
          placeholder="Room name"
        />
        <small id="roomInputHelp" class="form-text text-muted"
          >If the room doesn't exist yet, it will be created for you.</small
        >
      </div>
      <button type="button" id="roomConnect" class="btn btn-success">
        Connect
      </button>
    </div>
    <div class="col-12 col-md-4">
      <label for="roomSelect">Active rooms</label>
      <select multiple class="form-control" id="roomSelect">
        {% for room in rooms %}
        <option>{{ room }}</option>
        {% endfor %}
      </select>
    </div>
  </div>
</div>
<script src="{% static 'index.js' %}"></script>

{% endblock content %}

chat/templates/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Log-in</h1>
<p>Please, use the following form to log-in:</p>
<form method="post">
  {{ form.as_p }} {% csrf_token %}
  <p><input type="submit" value="Log-in" /></p>
</form>

<a href="{% url 'reg-page' %}">Not Register? Do it!</a>
{% endblock content %}

chat/templates/login_required.html
{% extends 'base.html' %}

{% block title %}
Login required!
{% endblock title %}

{% block content %}
    <div>Wait, wait, wait <a href={% url 'index-page' %}?next={{next_page}}>login</a> or <a href={% url 'reg-page' %}?next={{next_page}}>register</a> at first</div>
{% endblock content %}

chat/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand p-2" href="/">Navbar</a>
        <div class="btn-group p-3">
          <a type="button" class="dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{{ avatar_url }}" class="img-fluid dropdown-toggle rounded-circle" width="30" height="30" alt="{{ avatar_username }} avatar" id="avatar"></a>
          <ul class="dropdown-menu dropdown-menu-end">
            <li><a class="dropdown-item disabled" href="#">Action</a></li>
            <li><a class="dropdown-item disabled" href="#">Another action</a></li>
            <li><a class="dropdown-item disabled" href="#">Something else here</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'account-settings' %}">Settings</a></li>
            <li><a class="dropdown-item" href="{% url 'chat:logout' %}">Logout</a></li>
          </ul>
        </div>
    </ul>
  </div>
</nav>

chat/templates/reg.html
{% extends 'base.html' %}

{% block title %}
Registration page
{% endblock title %}

{% block content %}
<h1>Sign up</h1>

<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>

{% endblock content %}

chat/templates/room.html
{% extends 'base.html' %}

{% load static %}
{% load q_tags %}

{% block title %}
  django-channels-chat
{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/room.css' %}">
{% endblock style %}

{% block content %}
<div class="container mt-3 p-5">
  <h2 class="text-center">{{ room.name }}</h2>

  <div class="row">
    <div class="col-12 col-md-8">
      <div class="mb-2">
        <div id="chatLog">
          {% for message in messages %}
            <div class="message">
              <div class="message_user">
                <img src="{{ message.user.avatar.photo.url }}" width="40" height="40" class="avatar">
                <div>{{ message.user.username }}:</div>
              </div>

              <div class="message_text">
                <img src={{ message | get_attachment_url }} width="160" height="80" />
                {% if message.msg_type == 'PUBLIC' %}
                  <div class="message_text__conteiner">{{ message.content }}</div>
                {% else %}
                  {% if avatar_username == message.user.username %}
                    <div class="message_text__conteiner">PM to {{ message.to }}: {{ message.content }}</div>
                  {% else %}
                    <div class="message_text__conteiner">PM from {{ message.user.username }}: {{ message.content }}</div>
                  {% endif %}
                {% endif %}
                <div class="message_text__timestamp">{{ message.timestamp | date:"r"}}</div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>

      <form  id="sending_form">
        <div class="input-group">
          <div>
            <img src="#" alt="" id="q2" width="150" height="150">
          </div>
          <input
            type="text"
            class="form-control"
            id="chatMessageInput"
            placeholder="Enter your chat message"
          />
          <div class="input-group-append">
            <label class="btn btn-secondary">
            <input type="file" style="display:none" accepts="*">
            <i class="fa-solid fa-paperclip"></i>
            </label>
          </div>

          <div class="input-group-append">
            <button class="btn btn-success" id="chatMessageSend" type="button">
              Send
            </button>
          </div>
        </div>
      </form>
    </div>


    <div class="col-12 col-md-4" id="usersOnline">
      Online users
      <div class="form-control" id="onlineUsersSelector"></div>
    </div>
  </div>
  {{ room.name|json_script:"roomName" }}
</div>
<script src="{% static 'room.js' %}"></script>
{% endblock content %}