chat/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LogoutView

from .views import index_view, room_view, logout

app_name = 'chat'

urlpatterns = [
  path('', index_view, name='chat-index'),
  path('<str:room_name>/', room_view, name='chat-room'),
  path('logout', logout, name='logout')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

from core.settings import MEDIA_URL, MEDIA_ROOT
from chat.views import login_view, signup_view, login_required_view, account_settings

urlpatterns = [
    path('', login_view, name='index-page'),
    path('login-required', login_required_view, name='login-required'),
    # path('reg', SignUpView.as_view(), name='reg-page'),
    path('reg', signup_view, name='reg-page'),
    path('chat/', include('chat.urls')),
    path('account-settings', account_settings, name='account-settings'),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

chat/models.py
from curses.ascii import US
import os

from django.db import models
from django.contrib.auth.models import User

from core.settings import MEDIA_ROOT


default_image = os.path.join('avas', 'default.jpeg')



class Avatar(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(blank=False,
                              default=default_image,
                              upload_to='avas')
    
    def __str__(self):
        return f"{self.user.username} avatar"

class Room(models.Model):
    name = models.CharField(max_length=128)
    online = models.ManyToManyField(to=User, blank=True)

    def get_online_count(self):
        return self.online.count()

    def join(self, user):
        self.online.add(user)
        self.save()

    def __str__(self):
        return f'{self.name} ({self.get_online_count()})'


class PersonalChat(models.Model):
    pass


class CommunityChat(models.Model):
    pass


class Message(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    room = models.ForeignKey(to=Room, on_delete=models.CASCADE)
    content = models.CharField(max_length=512)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username}: {self.content} [{self.timestamp}]'

chat/forms.py
from dataclasses import field
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

from .models import Avatar
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class RegisterForm(UserCreationForm):
    username = forms.CharField(required=True)


    class Meta:
        model = User
        fields = ("username", "password1", "password2")

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.username = self.cleaned_data['username']
        if commit:
            user.save()
        avatar = Avatar.objects.create(user=user)
        avatar.save()
        return user

class AccountPhotoUpdateForm(forms.Form):
    photo = forms.ImageField(required=True)
    

chat/views.py
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout as lgt
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods

from .models import Avatar, Room
from .forms import LoginForm, RegisterForm, AccountPhotoUpdateForm

@require_http_methods(['GET', 'POST'])
def login_view(req):
  if req.method == 'GET':
    user = req.user
    if user.is_authenticated:
      return redirect('chat:chat-index')
    form = LoginForm()
    return render(req, 'login.html', {
      'form': form,
    })
  
  if req.method == 'POST':
    next_page = req.GET.get('next', 'chat:chat-index')
    form = LoginForm(req.POST)
    if form.is_valid():
      cd = form.cleaned_data
      user = authenticate(username=cd['username'], password=cd['password'])
      if user is None:
        return HttpResponse("Wrong password or username")
      login(req, user)
      return redirect(next_page)

@require_http_methods(['GET'])
@login_required(login_url='login-required')
def index_view(req):
    next_page = req.GET.get('next', 'chat:chat-index')
    return render(req, 'index.html', {
        'rooms': Room.objects.all(),
    })


@require_http_methods(['GET'])
@login_required(login_url='login-required')
def room_view(req, room_name):
  chat_room, created = Room.objects.get_or_create(name=room_name)
  path = Avatar.objects.get(user=req.user).photo
  return render(req, 'room.html', {
    'room': chat_room,
    'path': path,
    'req': req,
    'username': req.user.username,
  })


@login_required
def logout(req):
  lgt(req)
  return redirect('index-page')

@require_http_methods(['GET', 'POST'])
def signup_view(req):
    form = RegisterForm(req.POST)
    if form.is_valid():
        form.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(req, user)
        next_page = req.GET.get('next', 'chat:chat-index')
        return redirect(next_page)
    else:
        form = RegisterForm()
    return render(req, 'reg.html', {'form': form})

@require_http_methods(['GET'])
def login_required_view(req):
    next_page = req.GET.get('next', None)
    return render(req, "login_required.html", { 'next_page': next_page })

@require_http_methods(['GET', 'POST'])
def account_settings(req):
    # TODO: Crop avatar
    if req.method == 'GET':
        form = AccountPhotoUpdateForm()
        return render(req, 'account_settings.html', {
            'form': form,
            'prev_photo': Avatar.objects.get(user=req.user).photo.url,
        })
    if req.method == 'POST':
        form = AccountPhotoUpdateForm(req.POST, req.FILES)
        if form.is_valid():
            photo = form.cleaned_data['photo']
            print(photo)
            avatar = Avatar.objects.get(user=req.user)
            avatar.photo=photo
            avatar.save()
            return HttpResponse('OK')
        return HttpResponse('Wrong!', 405)

chat/templates/account_settings.html
{% load static %}

<h1>You settings</h1>

<form method="post"  enctype="multipart/form-data" id="form_img">
  {{ form.as_p }} {% csrf_token %}
  <img id="img_id" src="{{ prev_photo }}" alt="your image" />
  <p><input type="submit" value="Save" /></p>
</form>

<script src="{% static 'account_settings.js' %}"></script>

chat/templates/base.html
<!-- prettier-ignore -->
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock title %}</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
    />
    <link rel="shortcut icon" href="{% static 'favicon-16x16.png' %}" type="image/x-icon">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
    {% block style %}{% endblock style %}
  </head>
  <body>
    <div id="header">
      <span class="logo">Profile</span>
      <a href="{% url 'account-settings' %}"><span class="alert alert-info">Settings</span></a>
    </div>
    <div id="content">{% block content %} {% endblock %}</div>
  </body>
</html>

chat/templates/index.html
<!-- prettier-ignore -->
{% extends 'base.html' %}
{% load static %}

{% block title %} 
  django-channels-chat 
{% endblock title %} 

{% block style %}
<style>
  #roomSelect {
    height: 300px;
  }
</style>
{% endblock style %} {% block content %}
<div class="container mt-3 p-5">
  <h2>django-channels-chat</h2>
  <div class="row">
    <div class="col-12 col-md-8">
      <div class="mb-2">
        <label for="roomInput">Enter a room name to connect to it:</label>
        <input
          type="text"
          class="form-control"
          id="roomInput"
          placeholder="Room name"
        />
        <small id="roomInputHelp" class="form-text text-muted"
          >If the room doesn't exist yet, it will be created for you.</small
        >
      </div>
      <button type="button" id="roomConnect" class="btn btn-success">
        Connect
      </button>
    </div>
    <div class="col-12 col-md-4">
      <label for="roomSelect">Active rooms</label>
      <select multiple class="form-control" id="roomSelect">
        {% for room in rooms %}
        <option>{{ room }}</option>
        {% endfor %}
      </select>
    </div>
  </div>
</div>
<script src="{% static 'index.js' %}"></script>

{% endblock content %}

chat/templates/login.html
<!-- prettier-ignore -->
{% extends 'base.html' %}

{% block content %}
<h1>Log-in</h1>
<p>Please, use the following form to log-in:</p>
<form method="post">
  {{ form.as_p }} {% csrf_token %}
  <p><input type="submit" value="Log-in" /></p>
</form>

<a href="{% url 'reg-page' %}">Not Register? Do it!</a>
{% endblock content %}

chat/templates/login_required.html
{% extends 'base.html' %}

{% block title %}
Login required!
{% endblock title %}

{% block content %}
    <div>Wait, wait, wait <a href={% url 'index-page' %}?next={{next_page}}>login</a> or <a href={% url 'reg-page' %}?next={{next_page}}>register</a> at first</div>
{% endblock content %}

chat/templates/reg.html
{% extends 'base.html' %}

{% block title %}
Registration page
{% endblock title %}

{% block content %}
<h1>Sign up</h1>

<!--Register--> 
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>

{% endblock content %}

chat/templates/room.html
<!-- prettier-ignore -->
{% extends 'base.html' %}

{% load static %}

{% block title %} 
  django-channels-chat 
{% endblock title %} 

{% block style %}
<style>
  #chatLog {
    height: 300px;
    background-color: #ffffff;
    resize: none;
  }

  #onlineUsersSelector {
    height: 300px;
  }
</style>
{% endblock style %} {% block content %}
<div class="container mt-3 p-5">
  <h2>django-channels-chat</h2>

  <figure>
    <img src="http://{{ req.get_host }}/media/{{ path }}" />
    <figcaption>{{ username }}</figcaption>
  </figure>
  <a href="{% url 'chat:logout' %}">Logout</a>

  <div class="row">
    <div class="col-12 col-md-8">
      <div class="mb-2">
        <label for="chatLog">Room: #{{ room.name }}</label>
        <textarea
          class="form-control"
          id="chatLog"
          readonly
          autocomplete="off"
        ></textarea>
      </div>
      <div class="input-group">
        <input
          type="text"
          class="form-control"
          id="chatMessageInput"
          placeholder="Enter your chat message"
        />
        <div class="input-group-append">
          <button class="btn btn-success" id="chatMessageSend" type="button">
            Send
          </button>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-4">
      <label for="onlineUsers">Online users</label>
      <select multiple class="form-control" id="onlineUsersSelector"></select>
    </div>
  </div>
  {{ room.name|json_script:"roomName" }}
</div>
<script src="{% static 'room.js' %}"></script>
{% endblock content %}